version: '3'
services:
  compose-core:
    container_name: corehost
    image: "compose-core"
    build: core/
    ports:
    - "8082:8082"
    networks:
        testing_net:
            ipv4_address: 172.28.1.2
  compose-partner:
    container_name: partnerhost
    image: "compose-partner"
    build: partner/
    ports:
    - "8084:8084"
    networks:
        testing_net:
            ipv4_address: 172.28.1.4
  compose-ticket:
    container_name: tickethost
    image: "compose-ticket"
    build: ticket/
    ports:
    - "8083:8083"
    depends_on:
    - compose-core
    - compose-partner
    networks:
        testing_net:
            ipv4_address: 172.28.1.3
  compose-api:
    container_name: apihost
    image: "compose-api"
    build: api/
    ports:
    - "8081:8081"
    depends_on:
      - compose-core
      - compose-ticket
    networks:
        testing_net:
            ipv4_address: 172.28.1.1    
            
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16